- name: Установка пакетиков ...
  ansible.builtin.apt:
    name:
      - rsyslog
    state: present
    update_cache: true
  tags:
    - install packages
- name: Замена конфига rsyslog ...
  ansible.builtin.copy:
    src: files/rsyslog.conf
    dest: /etc/rsyslog.conf
    mode: '0644'
    force: true
  when: (ansible_hostname == "log")
  tags:
    - replace rsyslog config
- name: Запуск rsyslog ...
  ansible.builtin.systemd_service:
    name: rsyslog
    enabled: true
    state: restarted
  tags: restart rsyslog
  when: (ansible_hostname == "log")
