- name: Настройка NAT для сети
  ansible.builtin.iptables:
    action: "append"
    table: "nat"
    chain: "POSTROUTING"
    jump: "MASQUERADE"
    destination: "!192.168.0.0/16"
    out_interface: "eth0"
  tags:
    - set NAT on internal network
- name: Сохраняем настройки iptables в файл...
  community.general.iptables_state:
    state: saved
    path: /etc/iptables_rules.ipv4
  tags:
    - iptables-save
- name: Копируем скрипт для восстановления правила на постоянку...
  ansible.builtin.copy:
    src: "scripts/inet_ipv4_restore.sh"
    dest: "/etc/network/if-pre-up.d/iptables"
    owner: root
    group: root
    mode: "0755"
  tags:
    - iptables-restore
- name: Настраиваем маршруты для роутера...
  community.general.nmcli:
    conn_name: "eth1"
    routes4_extended:
      - ip: "192.168.0.0/16"
        next_hop: "192.168.255.2"
    state: present
  tags:
    - config routes on inetRouter
