- name: Настройка шлюзов по умолчанию для office1Server
  community.general.nmcli:
    conn_name: "eth1"
    gw4: "192.168.2.129"
    state: present
  tags:
    - gw4 on eth1 on office1Server
  when: (ansible_hostname == "office1Server")
- name: Настройка шлюзов по умолчанию для office2Server
  community.general.nmcli:
    conn_name: "eth1"
    gw4: "192.168.1.1"
    state: present
  tags:
    - gw4 on eth1 on office2Server
  when: (ansible_hostname == "office2Server")
- name: Настройка шлюзов по умолчанию для centralServer
  community.general.nmcli:
    conn_name: "eth1"
    gw4: "192.168.0.1"
    state: present
  tags:
    - gw4 on eth1 on centralServer
  when: (ansible_hostname == "centralServer")
