[options]
     UseSyslog
     Interface = eth1

[SSH]
     sequence = 7000,9000,8000
     seq_timeout = 5
     tcpflags = syn
     start_command = /sbin/iptables -I INPUT -i eth1 -s %IP% -p tcp --dport 22 -j ACCEPT
     stop_command = /sbin/iptables -D INPUT -i eth1 -s %IP% -p tcp --dport 22 -j ACCEPT
     cmd_timeout = 60