- name: Установка nginx ...
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  tags:
    - install nginx
- name: Замена конфига nginx ...
  ansible.builtin.copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    force: true
  tags:
    - replace nginx config
- name: Запуск nginx ...
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: restarted
  tags:
    - restart nginx
