- name: Добавление ключа elasticsearch ...
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
    executable: /bin/bash
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg
  tags:
    - add elasticsearch keyring
- name: Добавление репозитория elasticsearch ...
  ansible.builtin.copy:
    src: files/elastic-8.x.list
    dest: /etc/apt/sources.list.d/elastic-8.x.list
    force: true
    owner: root
    group: root
    mode: '0755'
  tags:
    - add elasticsearch repository
- name: Установка elasticsearch ...
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      [[ -f /etc/profile.d/elastic.sh ]] && rm -f /etc/profile.d/elastic.sh
      apt update && ELASTIC_PASSWORD=$(apt install elasticsearch -y \
      | grep 'The generated password for the elastic' | awk '{print $11}' | awk '{print $1}')
      ELASTIC_PASSWORD = ${ELASTIC_PASSWORD%??}
      echo "export ELASTIC_PASSWORD=$ELASTIC_PASSWORD" > /etc/profile.d/elastic.sh
      source /etc/profile.d/elastic.sh
    executable: /bin/bash
    creates: /etc/profile.d/elastic.sh
  tags:
    - install elasticsearch
- name: Запуск elasticsearch ...
  ansible.builtin.systemd_service:
    name: elasticsearch
    enabled: true
    state: restarted
    daemon_reload: true
  tags:
    - start elasticsearch
- name: Установка Kibana ...
  ansible.builtin.apt:
    name:
      - kibana
      - logstash
    update_cache: true
    state: present
  tags:
    - install Kibana
- name: Запуск Kibana ...
  ansible.builtin.systemd_service:
    name: kibana
    state: restarted
    enabled: true
- name: Запуск LogStash ...
  ansible.builtin.systemd_service:
    name: logstash
    state: restarted
    enabled: true
- name: Меняем IP адрес Kibana на рабочий
  ansible.builtin.replace:
    path: /etc/kibana/kibana.yml
    regexp: "#(server\.host)"
    replace: "\1"
- name: Добавление конфигов LogStash ...
  ansible.builtin.copy:
    src: "files/{{ sources }}"
    dest: /etc/logstash/conf.d/
    mode: '0644'
    owner: root
    group: root
  vars:
    sources:
      - filter.conf
      - input.conf
      - output.conf
  tags:
    - add LogStash configs
- name: Меняем пароль