- name: Настройка всех машин
  become: true
  hosts: all
  roles:
    - all
- name: Настройка inetRouter
  hosts: inetRouter
  roles:
    - inetRouter
- name: Настройка office1Router
  hosts: office1Router
  roles:
    - office1Router
- name: Настройка office2Router
  hosts: office2Router
  roles:
    - office2Router
- name: Настройка centralRouter
  hosts: centralRouter
  roles:
    - centralRouter
- name: Настройка серверов
  hosts: servers
  roles:
    - servers
